name: Docker CI

on:
  push:
    branches:
      - master
  pull_request: 
    branches:
      - master

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Setup .NET Environment
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x.x'
      
      - name: DELETE ME, THIS IS TEST
        run: echo "Hello, world!" > file.trx
      
      - name: DELETE ME, THIS IS ALSO TEST
        uses: actions/upload-artifacts@v4
        with: 
          name: test-artifact-1234
          path: '**/*.trx'
        
        #      - name: Restore .NET Solution
#        run: dotnet restore
#        
#      - name: Build .NET Solution
#        run: dotnet build --no-restore --configuration Release
#        
#      - name: Run .NET Test Projects
#        run: dotnet test --no-build --configuration Release
        
      