name: Docker CI

on:
  push:
    branches:
      - master
  pull_request: 
    branches:
      - master

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Setup .NET Environment
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x.x'
        
      - name: Restore .NET Solution
        run: dotnet restore

      - name: Build .NET Solution
        run: dotnet build --no-restore --configuration Release

      - name: Run .NET Test Projects
        run: dotnet test --no-build --configuration Release     
        
  deploy:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Set Up BuildX
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
      - name: Define Docker image tags
        id: vars
        run: |
          echo "latest=latest" >> $GITHUB_OUTPUT
          echo "commit-sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      
      - name: Push all docker image tags
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/ci-test:${{ steps.vars.outputs.commit-sha }}
            ${{ secrets.DOCKER_USERNAME }}/ci-test:${{ steps.vars.outputs.latest }}